### ISSUE TITLE
Can you write a readme?

### ISSUE THREAD

**Issue by FiveYellowMice** [K-Guan/xbzyw#1]
Without a readme, users won't know how to execute these scripts.

**Comment by K-Guan** [comment]
Yes I will, but after all of the scripts can work fine.

**Comment by K-Guan** [comment]
And by the way, check the `git log`. You will understand what do some of the scripts do.

**Comment by FiveYellowMice** [comment]
Yes, your commit messages are amazing...

**Comment by K-Guan** [comment]
好了，论我已经写了个README了。

**Comment by pigfromChina** [comment]
你好😏
